version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  client:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    links:
      - redis
    command: "bash -c 'echo Waiting for user action && \
                       sleep 360 '"


  random-generator:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    links:
      - redis
    command:
      - "java"
      - "-cp"
      - "./target/hitscounterapp-1.0-SNAPSHOT.jar:./target/dependency/*"
      - "com.hitscounter.app.RandomHitsProducerApp"
      - "redis"

  reader:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    links:
      - redis
    command:
      - "java"
      - "-cp"
      - "./target/hitscounterapp-1.0-SNAPSHOT.jar:./target/dependency/*"
      - "com.hitscounter.app.HitCountReaderApp"
      - "redis"
